name: Docker Deployment

on:
    workflow_run:  
        workflows: ["Basic CI", "Linting"]
        types:
            - completed

        branches:
            - main

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Reading Version
              id: version
              run: |
                VERSION=$(cat application_version.txt)
                echo "VERSION=$VERSION" >> $GITHUB_ENV
              shell: bash

            - name: Log in to Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Image
              run: |
                IMAGE=mohitkumhar/ai-support-hitl
                TAG=${{ env.VERSION }}
                docker build -f docker/Dockerfile -t $IMAGE:$TAG .
                docker push $IMAGE:$TAG

                docker build -f docker/Dockerfile -t $IMAGE:latest .
                docker push $IMAGE:latest

              shell: bash


